# Generated by Django 4.1.4 on 2024-07-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmp3',
            name='audio_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='requestmp3',
            name='text_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
