# Generated by Django 5.1.4 on 2025-03-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0004_alter_requestmp3_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmp3',
            name='requested_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
