# Generated by Django 5.1.4 on 2025-03-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0005_alter_requestmp3_requested_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmp3',
            name='audio_file',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
