# Generated by Django 5.1.4 on 2025-04-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0010_requestmp3_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmp3',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
